// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElSvgIcon: typeof import('./src/components/ElSvgIcon.vue')['default']
    ImgUpload: typeof import('./src/components/ImgUpload.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
